import React from 'react';
import {
    ClipboardList,
    Search,
    HelpCircle,
    AlertTriangle,
    BookOpen,
    Info
} from 'lucide-react';

const SummaryCard = ({ report }) => {
    const { aiSummary } = report;

    return (
        <div className="space-y-8 animate-in slide-in-from-right-4 duration-500 pb-20">
            {/* 1. Simplified Summary Card */}
            <div className="glass-card overflow-hidden">
                <div className="bg-gradient-to-r from-cyan-600 to-blue-700 px-6 py-4 flex items-center gap-3">
                    <ClipboardList className="w-5 h-5 text-white" />
                    <h2 className="font-bold text-white tracking-wide uppercase text-sm">Simplified Clinical Summary</h2>
                </div>
                <div className="p-8">
                    <p className="text-slate-100 leading-relaxed text-lg italic font-medium">
                        "{aiSummary.simplifiedSummary}"
                    </p>
                </div>
            </div>

            <div className="grid md:grid-cols-2 gap-8">
                {/* 2. Key Observations */}
                <div className="glass-card p-6 border-l-4 border-l-cyan-500">
                    <div className="flex items-center gap-3 mb-6">
                        <Search className="w-5 h-5 text-cyan-400" />
                        <h3 className="font-bold text-slate-200">Key Observations</h3>
                    </div>
                    <ul className="space-y-4">
                        {aiSummary.observations.map((item, index) => (
                            <li key={index} className="flex gap-3 text-sm text-slate-300 group">
                                <span className="text-cyan-500 font-bold">•</span>
                                <span className="leading-relaxed group-hover:text-slate-100 transition-colors">{item}</span>
                            </li>
                        ))}
                    </ul>
                </div>

                {/* 3. Important Context/Notes */}
                <div className="glass-card p-6 border-l-4 border-l-purple-500">
                    <div className="flex items-center gap-3 mb-6">
                        <Info className="w-5 h-5 text-purple-400" />
                        <h3 className="font-bold text-slate-200">Important Context</h3>
                    </div>
                    <p className="text-sm text-slate-300 leading-relaxed">
                        {aiSummary.importantNotes || "No specific secondary notes found in this report."}
                    </p>
                </div>
            </div>

            {/* 4. Terminology Explainer */}
            <div className="glass-card p-6">
                <div className="flex items-center gap-3 mb-6">
                    <BookOpen className="w-5 h-5 text-cyan-400" />
                    <h3 className="font-bold text-slate-200">Medical Terminology Explained</h3>
                </div>
                <div className="grid sm:grid-cols-2 gap-4">
                    {aiSummary.terminology.map((item, index) => (
                        <div key={index} className="bg-[#2D333B]/50 p-4 rounded-xl border border-slate-700/50 hover:border-cyan-500/30 transition-all">
                            <span className="block font-bold text-cyan-400 text-sm mb-1">{item.term}</span>
                            <span className="text-xs text-slate-400 leading-normal">{item.meaning}</span>
                        </div>
                    ))}
                </div>
            </div>

            {/* 5. Health Disclaimer */}
            <div className="bg-red-500/5 border border-red-500/20 rounded-2xl p-6 flex gap-4">
                <AlertTriangle className="w-6 h-6 text-red-500 flex-shrink-0" />
                <div className="space-y-2">
                    <h4 className="font-bold text-red-400 text-sm">Medical Accuracy Disclaimer</h4>
                    <p className="text-xs text-slate-400 leading-relaxed">
                        This summary is generated by an Artificial Intelligent model. While it aims for accuracy, it is not a medical professional.
                        <strong> Always consult with your primary care physician or a qualified specialist to interpret these results.</strong>
                    </p>
                </div>
            </div>

            {/* 6. Original Report Text */}
            <div className="glass-card p-6">
                <div className="flex items-center gap-3 mb-6">
                    <BookOpen className="w-5 h-5 text-purple-400" />
                    <h3 className="font-bold text-slate-200">Original MRI Report</h3>
                </div>
                <div className="bg-[#1C2128] p-6 rounded-xl border border-slate-700/50">
                    <p className="text-slate-400 text-sm leading-relaxed whitespace-pre-wrap font-mono">
                        {report.reportText}
                    </p>
                </div>
            </div>
        </div>
    );
};

export default SummaryCard;
